# Benjamin Lucas

<img src="/assets/headshot_image.png" alt="Benjamin Lucas" style="width:200px;"/>

Expert in AI and ML with a background in education, pastoral leadership, and project management.

show_downloads: true

theme: jekyll-theme-minimal

