title: Benjamin Lucas
logo: /assets/headshot_image.png
description: Expert in AI and ML with a background in education, pastoral leadership, and project management.
# show_downloads: true
theme: jekyll-theme-minimal
