title: Benjamin Lucas
logo: /assets/headshot_image_resized.png
description: Expert in AI and ML with a background in education and project management.
show_downloads: false
theme: jekyll-theme-minimal
