title: Benjamin Lucas
# logo: /assets.img/headshot_circle.png # Need to create 'assets' folder and add this picture
# description: Expert in AI and ML with a background in education, pastoral leadership, and project management.
# show_downloads: true
theme: jekyll-theme-minimal
