title: Benjamin Lucas
logo: /assets/headshot_circle.png
description: Data Scientist with NLP, ML, and gen-AI expertise and unique background in education, pastoral leadership, and project management.
theme: jekyll-theme-minimal
