title: Benjamin Lucas
description: >- # this means to ignore newlines until "baseurl:"
  Expert in AI and ML with a background in education, pastoral leadership, and project management.
theme: jekyll-theme-minimal

