title: Benjamin Lucas
logo: /assets/headshot_circle.png
description: Data Scientist with ML, NLP, and gen-AI expertise and a unique background in education, pastoral leadership, and project management.
theme: jekyll-theme-minimal
