title: Benjamin Lucas
logo: /assets/headshot_circle.png
description: Data Scientist with expertise in ML, NLP, and generative AI and a unique background in education, pastoral leadership, and project management.
theme: jekyll-theme-minimal
